# Generated by Django 3.0.4 on 2020-03-28 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=180, null=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('short_content', models.TextField(blank=True, null=True, verbose_name='Short Content')),
                ('archive', models.BooleanField(default=False, verbose_name='Archive')),
                ('published', models.BooleanField(default=True, verbose_name='published')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='djBlog.Category', verbose_name='Category')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djBlog.Media', verbose_name='Cover Image')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='djblog_post_created', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='djBlog.Tag', verbose_name='Tag')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='djblog_post_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='react',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacts', to='djBlog.Post'),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
