# Generated by Django 3.0.4 on 2020-03-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djBlog', '0002_auto_20200328_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, null=True, verbose_name='Slug'),
        ),
    ]
