# Generated by Django 3.0.4 on 2020-03-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djBlog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
