# Generated by Django 3.0.4 on 2020-03-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='m_cover_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='sm_cover_image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
    ]
