# Generated by Django 3.0.4 on 2020-03-28 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dblog', '0002_auto_20200328_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='dblog.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dblog.Media', verbose_name='Cover Image'),
        ),
    ]
