# Generated by Django 3.0.4 on 2020-03-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djBlog', '0005_auto_20200328_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='djBlog.Post', verbose_name='Post'),
        ),
    ]
