# Generated by Django 3.0.4 on 2020-03-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblog', '0006_blog_short_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True, verbose_name='Slug'),
        ),
    ]
