# Generated by Django 3.0.4 on 2020-03-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djBlog', '0007_auto_20200328_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='status',
            new_name='active',
        ),
    ]
