# Generated by Django 3.0.4 on 2020-03-25 18:30

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblog', '0007_auto_20200325_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/blog/images/'), upload_to='', verbose_name='Cover Image'),
        ),
    ]
