# Generated by Django 3.0.4 on 2020-03-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblog', '0008_blog_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archive'),
        ),
    ]
