# Generated by Django 3.0.4 on 2020-03-28 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djBlog', '0009_auto_20200328_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='djBlog.Comment', verbose_name='Parent Comment'),
        ),
    ]
