# Generated by Django 3.0.4 on 2020-03-26 07:19

import dblog.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblog', '0010_react'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=dblog.files.blog_image_upload_path, verbose_name='Cover Image'),
        ),
    ]
