# Generated by Django 3.0.4 on 2020-03-29 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djBlog', '0010_auto_20200328_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJSiteInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Site Title')),
                ('tagline', models.CharField(blank=True, max_length=80, null=True, verbose_name='Tag Line')),
                ('footer_text', models.CharField(blank=True, max_length=150, null=True, verbose_name='Footer Text')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='djblog_djsiteinformation_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='djblog_djsiteinformation_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
