# Generated by Django 3.0.4 on 2020-03-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djBlog', '0011_djsiteinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='djsiteinformation',
            name='header_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Header Title'),
        ),
    ]
