# Generated by Django 3.0.4 on 2020-03-27 04:21

import dblog.files
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblog', '0012_auto_20200326_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='m_cover_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/blog/images/'), upload_to=dblog.files.m_cover_image_upload_path, verbose_name='Medium Cover Image'),
        ),
        migrations.AddField(
            model_name='blog',
            name='sm_cover_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/blog/images/'), upload_to=dblog.files.sm_cover_image_upload_path, verbose_name='Small Cover Image'),
        ),
    ]
